/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as GamesCodeLobbyRouteImport } from './routes/games/$code/lobby'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiUsersUsernameStatsRouteImport } from './routes/api/users/$username/stats'
import { Route as ApiGamesCodeStartRouteImport } from './routes/api/games/$code/start'
import { Route as ApiGamesCodePlayRouteImport } from './routes/api/games/$code/play'
import { Route as ApiGamesCodePickRouteImport } from './routes/api/games/$code/pick'
import { Route as ApiGamesCodeJoinRouteImport } from './routes/api/games/$code/join'
import { Route as ApiGamesCodeEventsRouteImport } from './routes/api/games/$code/events'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeLobbyRoute = GamesCodeLobbyRouteImport.update({
  id: '/games/$code/lobby',
  path: '/games/$code/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUsernameStatsRoute = ApiUsersUsernameStatsRouteImport.update({
  id: '/api/users/$username/stats',
  path: '/api/users/$username/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeStartRoute = ApiGamesCodeStartRouteImport.update({
  id: '/api/games/$code/start',
  path: '/api/games/$code/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodePlayRoute = ApiGamesCodePlayRouteImport.update({
  id: '/api/games/$code/play',
  path: '/api/games/$code/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodePickRoute = ApiGamesCodePickRouteImport.update({
  id: '/api/games/$code/pick',
  path: '/api/games/$code/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeJoinRoute = ApiGamesCodeJoinRouteImport.update({
  id: '/api/games/$code/join',
  path: '/api/games/$code/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeEventsRoute = ApiGamesCodeEventsRouteImport.update({
  id: '/api/games/$code/events',
  path: '/api/games/$code/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$code/events': typeof ApiGamesCodeEventsRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/pick': typeof ApiGamesCodePickRoute
  '/api/games/$code/play': typeof ApiGamesCodePlayRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/users/$username/stats': typeof ApiUsersUsernameStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/games/$code/events': typeof ApiGamesCodeEventsRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/pick': typeof ApiGamesCodePickRoute
  '/api/games/$code/play': typeof ApiGamesCodePlayRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/users/$username/stats': typeof ApiUsersUsernameStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$code/events': typeof ApiGamesCodeEventsRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/pick': typeof ApiGamesCodePickRoute
  '/api/games/$code/play': typeof ApiGamesCodePlayRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/users/$username/stats': typeof ApiUsersUsernameStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/games/create'
    | '/games/join'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/games/$code/lobby'
    | '/api/games/'
    | '/api/games/$code/events'
    | '/api/games/$code/join'
    | '/api/games/$code/pick'
    | '/api/games/$code/play'
    | '/api/games/$code/start'
    | '/api/users/$username/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/games/create'
    | '/games/join'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/games/$code/lobby'
    | '/api/games'
    | '/api/games/$code/events'
    | '/api/games/$code/join'
    | '/api/games/$code/pick'
    | '/api/games/$code/play'
    | '/api/games/$code/start'
    | '/api/users/$username/stats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/games/create'
    | '/games/join'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/games/$code/lobby'
    | '/api/games/'
    | '/api/games/$code/events'
    | '/api/games/$code/join'
    | '/api/games/$code/pick'
    | '/api/games/$code/play'
    | '/api/games/$code/start'
    | '/api/users/$username/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  GamesCreateRoute: typeof GamesCreateRoute
  GamesJoinRoute: typeof GamesJoinRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  GamesCodeLobbyRoute: typeof GamesCodeLobbyRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiGamesCodeEventsRoute: typeof ApiGamesCodeEventsRoute
  ApiGamesCodeJoinRoute: typeof ApiGamesCodeJoinRoute
  ApiGamesCodePickRoute: typeof ApiGamesCodePickRoute
  ApiGamesCodePlayRoute: typeof ApiGamesCodePlayRoute
  ApiGamesCodeStartRoute: typeof ApiGamesCodeStartRoute
  ApiUsersUsernameStatsRoute: typeof ApiUsersUsernameStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/lobby': {
      id: '/games/$code/lobby'
      path: '/games/$code/lobby'
      fullPath: '/games/$code/lobby'
      preLoaderRoute: typeof GamesCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$username/stats': {
      id: '/api/users/$username/stats'
      path: '/api/users/$username/stats'
      fullPath: '/api/users/$username/stats'
      preLoaderRoute: typeof ApiUsersUsernameStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/start': {
      id: '/api/games/$code/start'
      path: '/api/games/$code/start'
      fullPath: '/api/games/$code/start'
      preLoaderRoute: typeof ApiGamesCodeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/play': {
      id: '/api/games/$code/play'
      path: '/api/games/$code/play'
      fullPath: '/api/games/$code/play'
      preLoaderRoute: typeof ApiGamesCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/pick': {
      id: '/api/games/$code/pick'
      path: '/api/games/$code/pick'
      fullPath: '/api/games/$code/pick'
      preLoaderRoute: typeof ApiGamesCodePickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/join': {
      id: '/api/games/$code/join'
      path: '/api/games/$code/join'
      fullPath: '/api/games/$code/join'
      preLoaderRoute: typeof ApiGamesCodeJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/events': {
      id: '/api/games/$code/events'
      path: '/api/games/$code/events'
      fullPath: '/api/games/$code/events'
      preLoaderRoute: typeof ApiGamesCodeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  GamesCreateRoute: GamesCreateRoute,
  GamesJoinRoute: GamesJoinRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  GamesCodeLobbyRoute: GamesCodeLobbyRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiGamesCodeEventsRoute: ApiGamesCodeEventsRoute,
  ApiGamesCodeJoinRoute: ApiGamesCodeJoinRoute,
  ApiGamesCodePickRoute: ApiGamesCodePickRoute,
  ApiGamesCodePlayRoute: ApiGamesCodePlayRoute,
  ApiGamesCodeStartRoute: ApiGamesCodeStartRoute,
  ApiUsersUsernameStatsRoute: ApiUsersUsernameStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
