/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiPacksRouteImport } from './routes/api/packs'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as GamesCodeSessionRouteImport } from './routes/games/$code/session'
import { Route as GamesCodeLobbyRouteImport } from './routes/games/$code/lobby'
import { Route as GamesCodeEndRouteImport } from './routes/games/$code/end'
import { Route as ApiGamesCodeWsRouteImport } from './routes/api/games/$code/ws'
import { Route as ApiGamesCodeStartRouteImport } from './routes/api/games/$code/start'
import { Route as ApiGamesCodeLeaveRouteImport } from './routes/api/games/$code/leave'
import { Route as ApiGamesCodeJoinRouteImport } from './routes/api/games/$code/join'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksRoute = ApiPacksRouteImport.update({
  id: '/api/packs',
  path: '/api/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeSessionRoute = GamesCodeSessionRouteImport.update({
  id: '/games/$code/session',
  path: '/games/$code/session',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeLobbyRoute = GamesCodeLobbyRouteImport.update({
  id: '/games/$code/lobby',
  path: '/games/$code/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeEndRoute = GamesCodeEndRouteImport.update({
  id: '/games/$code/end',
  path: '/games/$code/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeWsRoute = ApiGamesCodeWsRouteImport.update({
  id: '/api/games/$code/ws',
  path: '/api/games/$code/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeStartRoute = ApiGamesCodeStartRouteImport.update({
  id: '/api/games/$code/start',
  path: '/api/games/$code/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeLeaveRoute = ApiGamesCodeLeaveRouteImport.update({
  id: '/api/games/$code/leave',
  path: '/api/games/$code/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCodeJoinRoute = ApiGamesCodeJoinRouteImport.update({
  id: '/api/games/$code/join',
  path: '/api/games/$code/join',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/packs': typeof ApiPacksRoute
  '/api/stats': typeof ApiStatsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games/$code/end': typeof GamesCodeEndRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/session': typeof GamesCodeSessionRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/leave': typeof ApiGamesCodeLeaveRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/games/$code/ws': typeof ApiGamesCodeWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/packs': typeof ApiPacksRoute
  '/api/stats': typeof ApiStatsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games/$code/end': typeof GamesCodeEndRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/session': typeof GamesCodeSessionRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/leave': typeof ApiGamesCodeLeaveRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/games/$code/ws': typeof ApiGamesCodeWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/packs': typeof ApiPacksRoute
  '/api/stats': typeof ApiStatsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/games/$code/end': typeof GamesCodeEndRoute
  '/games/$code/lobby': typeof GamesCodeLobbyRoute
  '/games/$code/session': typeof GamesCodeSessionRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$code/join': typeof ApiGamesCodeJoinRoute
  '/api/games/$code/leave': typeof ApiGamesCodeLeaveRoute
  '/api/games/$code/start': typeof ApiGamesCodeStartRoute
  '/api/games/$code/ws': typeof ApiGamesCodeWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/api/config'
    | '/api/healthz'
    | '/api/packs'
    | '/api/stats'
    | '/games/create'
    | '/games/join'
    | '/games/$code/end'
    | '/games/$code/lobby'
    | '/games/$code/session'
    | '/api/games/'
    | '/api/games/$code/join'
    | '/api/games/$code/leave'
    | '/api/games/$code/start'
    | '/api/games/$code/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/api/config'
    | '/api/healthz'
    | '/api/packs'
    | '/api/stats'
    | '/games/create'
    | '/games/join'
    | '/games/$code/end'
    | '/games/$code/lobby'
    | '/games/$code/session'
    | '/api/games'
    | '/api/games/$code/join'
    | '/api/games/$code/leave'
    | '/api/games/$code/start'
    | '/api/games/$code/ws'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/api/config'
    | '/api/healthz'
    | '/api/packs'
    | '/api/stats'
    | '/games/create'
    | '/games/join'
    | '/games/$code/end'
    | '/games/$code/lobby'
    | '/games/$code/session'
    | '/api/games/'
    | '/api/games/$code/join'
    | '/api/games/$code/leave'
    | '/api/games/$code/start'
    | '/api/games/$code/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiPacksRoute: typeof ApiPacksRoute
  ApiStatsRoute: typeof ApiStatsRoute
  GamesCreateRoute: typeof GamesCreateRoute
  GamesJoinRoute: typeof GamesJoinRoute
  GamesCodeEndRoute: typeof GamesCodeEndRoute
  GamesCodeLobbyRoute: typeof GamesCodeLobbyRoute
  GamesCodeSessionRoute: typeof GamesCodeSessionRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiGamesCodeJoinRoute: typeof ApiGamesCodeJoinRoute
  ApiGamesCodeLeaveRoute: typeof ApiGamesCodeLeaveRoute
  ApiGamesCodeStartRoute: typeof ApiGamesCodeStartRoute
  ApiGamesCodeWsRoute: typeof ApiGamesCodeWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs': {
      id: '/api/packs'
      path: '/api/packs'
      fullPath: '/api/packs'
      preLoaderRoute: typeof ApiPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/session': {
      id: '/games/$code/session'
      path: '/games/$code/session'
      fullPath: '/games/$code/session'
      preLoaderRoute: typeof GamesCodeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/lobby': {
      id: '/games/$code/lobby'
      path: '/games/$code/lobby'
      fullPath: '/games/$code/lobby'
      preLoaderRoute: typeof GamesCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code/end': {
      id: '/games/$code/end'
      path: '/games/$code/end'
      fullPath: '/games/$code/end'
      preLoaderRoute: typeof GamesCodeEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/ws': {
      id: '/api/games/$code/ws'
      path: '/api/games/$code/ws'
      fullPath: '/api/games/$code/ws'
      preLoaderRoute: typeof ApiGamesCodeWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/start': {
      id: '/api/games/$code/start'
      path: '/api/games/$code/start'
      fullPath: '/api/games/$code/start'
      preLoaderRoute: typeof ApiGamesCodeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/leave': {
      id: '/api/games/$code/leave'
      path: '/api/games/$code/leave'
      fullPath: '/api/games/$code/leave'
      preLoaderRoute: typeof ApiGamesCodeLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$code/join': {
      id: '/api/games/$code/join'
      path: '/api/games/$code/join'
      fullPath: '/api/games/$code/join'
      preLoaderRoute: typeof ApiGamesCodeJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiPacksRoute: ApiPacksRoute,
  ApiStatsRoute: ApiStatsRoute,
  GamesCreateRoute: GamesCreateRoute,
  GamesJoinRoute: GamesJoinRoute,
  GamesCodeEndRoute: GamesCodeEndRoute,
  GamesCodeLobbyRoute: GamesCodeLobbyRoute,
  GamesCodeSessionRoute: GamesCodeSessionRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiGamesCodeJoinRoute: ApiGamesCodeJoinRoute,
  ApiGamesCodeLeaveRoute: ApiGamesCodeLeaveRoute,
  ApiGamesCodeStartRoute: ApiGamesCodeStartRoute,
  ApiGamesCodeWsRoute: ApiGamesCodeWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
